import { Schema } from '@aws-amplify/datastore';

export const schema: Schema = {
  models: {
    Job: {
      name: 'Job',
      fields: {
        id: {
          name: 'id',
          isArray: false,
          type: 'ID',
          isRequired: true,
          attributes: [],
        },
        jobId: {
          name: 'jobId',
          isArray: false,
          type: 'String',
          isRequired: true,
          attributes: [],
        },
        title: {
          name: 'title',
          isArray: false,
          type: 'String',
          isRequired: true,
          attributes: [],
        },
        company: {
          name: 'company',
          isArray: false,
          type: 'String',
          isRequired: true,
          attributes: [],
        },
        location: {
          name: 'location',
          isArray: false,
          type: 'String',
          isRequired: false,
          attributes: [],
        },
        description: {
          name: 'description',
          isArray: false,
          type: 'String',
          isRequired: false,
          attributes: [],
        },
        pendingSync: {
          name: 'pendingSync',
          isArray: false,
          type: 'Boolean',
          isRequired: false,
          attributes: [],
        },
        lastSyncedAt: {
          name: 'lastSyncedAt',
          isArray: false,
          type: 'AWSDateTime',
          isRequired: false,
          attributes: [],
        },
        salary: {
          name: 'salary',
          isArray: false,
          type: 'Float',
          isRequired: false,
          attributes: [],
        },
        postedAt: {
          name: 'postedAt',
          isArray: false,
          type: 'AWSDateTime',
          isRequired: true,
          attributes: [],
        },
      },
      syncable: true,
      pluralName: 'Jobs',
      attributes: [
        { type: 'model', properties: {} },
        { type: 'key', properties: { name: 'byJob', fields: ['jobId'] } },
      ],
    },
    Experience: {
      name: 'Experience',
      fields: {
        id: {
          name: 'id',
          isArray: false,
          type: 'ID',
          isRequired: true,
          attributes: [],
        },
        userId: {
          name: 'userId',
          isArray: false,
          type: 'String',
          isRequired: true,
          attributes: [],
        },
        experienceId: {
          name: 'experienceId',
          isArray: false,
          type: 'String',
          isRequired: true,
          attributes: [],
        },
        title: {
          name: 'title',
          isArray: false,
          type: 'String',
          isRequired: true,
          attributes: [],
        },
        company: {
          name: 'company',
          isArray: false,
          type: 'String',
          isRequired: true,
          attributes: [],
        },
        startDate: {
          name: 'startDate',
          isArray: false,
          type: 'AWSDateTime',
          isRequired: true,
          attributes: [],
        },
        endDate: {
          name: 'endDate',
          isArray: false,
          type: 'AWSDateTime',
          isRequired: false,
          attributes: [],
        },
        description: {
          name: 'description',
          isArray: false,
          type: 'String',
          isRequired: false,
          attributes: [],
        },
      },
      syncable: true,
      pluralName: 'Experiences',
      attributes: [
        { type: 'model', properties: {} },
        { type: 'key', properties: { name: 'byUser', fields: ['userId'] } },
      ],
    },
    Application: {
      name: 'Application',
      fields: {
        id: {
          name: 'id',
          isArray: false,
          type: 'ID',
          isRequired: true,
          attributes: [],
        },
        userId: {
          name: 'userId',
          isArray: false,
          type: 'String',
          isRequired: true,
          attributes: [],
        },
        applicationId: {
          name: 'applicationId',
          isArray: false,
          type: 'String',
          isRequired: true,
          attributes: [],
        },
        jobId: {
          name: 'jobId',
          isArray: false,
          type: 'String',
          isRequired: true,
          attributes: [],
        },
        jobTitle: {
          name: 'jobTitle',
          isArray: false,
          type: 'String',
          isRequired: false,
          attributes: [],
        },
        jobCompany: {
          name: 'jobCompany',
          isArray: false,
          type: 'String',
          isRequired: false,
          attributes: [],
        },
        jobLocation: {
          name: 'jobLocation',
          isArray: false,
          type: 'String',
          isRequired: false,
          attributes: [],
        },
        jobSource: {
          name: 'jobSource',
          isArray: false,
          type: 'String',
          isRequired: false,
          attributes: [],
        },
        status: {
          name: 'status',
          isArray: false,
          type: 'String',
          isRequired: true,
          attributes: [],
        },
        appliedAt: {
          name: 'appliedAt',
          isArray: false,
          type: 'AWSDateTime',
          isRequired: true,
          attributes: [],
        },
        notes: {
          name: 'notes',
          isArray: false,
          type: 'String',
          isRequired: false,
          attributes: [],
        },
        pendingSync: {
          name: 'pendingSync',
          isArray: false,
          type: 'Boolean',
          isRequired: false,
          attributes: [],
        },
        lastSyncedAt: {
          name: 'lastSyncedAt',
          isArray: false,
          type: 'AWSDateTime',
          isRequired: false,
          attributes: [],
        },
      },
      syncable: true,
      pluralName: 'Applications',
      attributes: [
        { type: 'model', properties: {} },
        { type: 'key', properties: { name: 'byUser', fields: ['userId'] } },
      ],
    },
  },
  enums: {},
  nonModels: {},
  codegenVersion: '3.4.0',
  version: '1',
};
